### ISSUE TITLE
flag to skip all border related styles

### ISSUE THREAD

**Issue by etylsarin** [rsanchez/postcss-colors-only#2]
Hi @rsanchez 

First of all, thanks for creating this useful plugin!
Have just one question, would it be hard to add an option to skip all border related styles?

Cheers,
Filip

**Comment by mzohaibqc** [comment]
I found a bug,
src:
```
  .app__hr___2U3ua {
    margin: 40px 0;
    height: 1px;
    border: 0;
    background: #ccc;
  }
```
output:
```
.App__hr___2U3ua {
    border-color: 0;
    background-color: #ccc;
  }
```

**Comment by rsanchez** [comment]
There is currently no option to skip certain styles.
